### PR TITLE
Add Signature functionality

### PR DESCRIPTION
**Pull request by ryzokuken**
/cc @mcollina @tniessen @joepie91

### CODE REVIEW

**Comment by mcollina** [comment]
unit tests are missing ;)

**Comment by ryzokuken** [comment]
@mcollina they are! Will add them as soon as I can.

**Comment by ryzokuken** [comment]
@mcollina added tests, PTAL.

@tniessen two of the tests fail (I cannot manage to make it work with buffer and object keys). Let's sort this out. I will also check out the core tests for clarification.

**Comment by ryzokuken** [comment]
P.S. This commit introduces failing tests but I'd rather have failing tests to stay updated on the state of core than having less coverage just to have all-greens.

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by ryzokuken** [comment]
Removed the `docs` folder for now. Merging this. Thanks @mcollina.

**Pull request merged**
